[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
FLASK_ENV = "production"
PYTHON_VERSION = "3.11.0"
